[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src"
]

[contracts]
DVT = ["src/damn_valuable_token.cairo"]
truster = ["src/truster/truster_lender_pool.cairo"]